version: 2
updates:
  - package-ecosystem: gomod
    directory: /api
    schedule: { interval: weekly }
    groups:
      go: { patterns: ["*"] }

  - package-ecosystem: npm
    directory: /e2e
    schedule: { interval: weekly }
    groups:
      dev: { patterns: ["*"] }

  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    groups:
      actions: { patterns: ["*"] }

  - package-ecosystem: docker
    directory: /deploy
    schedule: { interval: weekly }
