// Command gen-scoring-table emits the frontend's copy of the point values.
//
// The scoring screen updates optimistically, so it needs to know what a tap is
// worth before the server answers. Hand-copying the rules into JavaScript
// would guarantee the two drift apart, and the drift would be silent: the
// screen would simply show a number the server disagrees with.
//
// So the table is generated by asking the real rules engine for every
// combination. If a rule changes in Go, this file changes with it, and CI
// fails if it was not regenerated.
//
// Run: go generate ./...
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/fetchandscore/fetchandscore/api/internal/scoring"
)

//go:generate go run . -out ../../../web/js/scoring-table.js

func main() {
	out := flag.String("out", "../../../web/js/scoring-table.js", "file to write")
	flag.Parse()

	if err := os.WriteFile(*out, []byte(generate()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	fmt.Println("wrote", *out)
}

func generate() string {
	var b strings.Builder

	b.WriteString(`// Code generated by cmd/gen-scoring-table. DO NOT EDIT.
//
// Point values mirrored from api/internal/scoring so the scoring screen can
// show a tap's worth immediately, without waiting for the server. The server
// remains authoritative: its total overwrites the optimistic one on every
// response, which is what applies the caps this table cannot know about
// (the 90:/5 top-five selection and the tiny-dog weekly ceiling).
//
// Regenerate with: go generate ./...

`)

	// The table is keyed by division because the junior exception changes what
	// a short catch is worth, and by tiny because of the per-catch bonus.
	b.WriteString("const TABLE = {\n")
	for _, division := range scoring.AllDivisions() {
		fmt.Fprintf(&b, "  %s: {\n", division)
		for _, tiny := range []bool{false, true} {
			key := "standard"
			if tiny {
				key = "tiny"
			}
			fmt.Fprintf(&b, "    %s: {\n", key)

			flags := scoring.Flags{Tiny: tiny, Division: division}
			for _, zone := range scoring.AllZones() {
				plain := scoring.ScoreThrow(scoring.Throw{Zone: zone}, flags).Points()
				air := scoring.ScoreThrow(scoring.Throw{Zone: zone, Air: true}, flags).Points()
				fmt.Fprintf(&b, "      %q: { plain: %s, air: %s },\n",
					zone, formatPoints(plain), formatPoints(air))
			}
			b.WriteString("    },\n")
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n\n")

	b.WriteString(`/**
 * What one throw is worth, in points.
 *
 * @param {string} zone            zone key, e.g. "30-40"
 * @param {boolean} air            a clear four-paws-off catch
 * @param {object} team
 * @param {boolean} team.tiny
 * @param {string} team.division
 */
export function pointsFor(zone, air, { tiny = false, division = 'expert' } = {}) {
  const byTiny = TABLE[division] ?? TABLE.expert;
  const values = (tiny ? byTiny.tiny : byTiny.standard)[zone];
  if (!values) return 0;
  return air ? values.air : values.plain;
}

`)

	// The button grid, in the order it is laid out: longest throw at the top,
	// because that is where the eye goes first and where the points are.
	b.WriteString("/** The scoring grid, furthest zone first. */\nexport const ZONE_BUTTONS = [\n")
	for _, zone := range []scoring.Zone{
		scoring.Zone40_50, scoring.Zone30_40, scoring.Zone20_30, scoring.Zone10_20,
	} {
		fmt.Fprintf(&b, "  { zone: %q, label: %q, tone: %q },\n",
			zone, zone.String()+" yd", toneFor(zone))
	}
	b.WriteString("];\n")

	return b.String()
}

// formatPoints renders a value that may be a half, without a trailing .0 on
// whole numbers.
func formatPoints(v float64) string {
	if v == float64(int(v)) {
		return fmt.Sprintf("%d", int(v))
	}
	return fmt.Sprintf("%.1f", v)
}

// toneFor maps a zone to its colour token in the stylesheet.
func toneFor(z scoring.Zone) string {
	switch z {
	case scoring.Zone40_50:
		return "zone-5"
	case scoring.Zone30_40:
		return "zone-3"
	case scoring.Zone20_30:
		return "zone-2"
	case scoring.Zone10_20:
		return "zone-1"
	default:
		return "zone-0"
	}
}
