#!/usr/bin/env bash
#
# Generates the timer's spoken cues as a single audio sprite plus an offset map.
#
# Why a sprite generated ahead of time, rather than the browser's speechSynthesis:
# the countdown has to be right. Live synthesis has unpredictable latency, a
# voice that differs on every device, and on iOS it can silently drop an
# utterance. A decoded AudioBuffer scheduled on the WebAudio clock is
# sample-accurate and identical everywhere.
#
# One sprite rather than a dozen files so the whole cue set is a single fetch
# and a single decode, done once when the scorekeeper taps START.
#
# Run: ./generate.sh   (needs espeak-ng and ffmpeg)
# The outputs are committed, so this only needs re-running to change the voice.

set -euo pipefail
cd "$(dirname "$0")"

# The voice. espeak-ng is robotic but perfectly clear at arm's length outdoors,
# which is the actual requirement. Swap this for a neural TTS if a nicer voice
# is wanted; nothing downstream cares, it just reads the sprite and offsets.
VOICE="${VOICE:-en-us+f3}"
SPEED="${SPEED:-150}"
PITCH="${PITCH:-45}"

# Cue key -> spoken text. Keys are what the client asks for.
CUES=(
  "ready:Ready"
  "set:Set"
  "go:Go"
  "sixty:Sixty seconds"
  "thirty:Thirty seconds"
  "fifteen:Fifteen seconds"
  "ten:Ten seconds"
  "five:Five"
  "four:Four"
  "three:Three"
  "two:Two"
  "one:One"
  "time:Time"
)

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "Generating ${#CUES[@]} cues with espeak-ng ($VOICE)..."

LIST="$WORK/list.txt"
: > "$LIST"
OFFSET=0
ENTRIES=()

for entry in "${CUES[@]}"; do
  key="${entry%%:*}"
  text="${entry#*:}"
  raw="$WORK/$key.raw.wav"
  clip="$WORK/$key.wav"

  espeak-ng -v "$VOICE" -s "$SPEED" -p "$PITCH" -w "$raw" "$text"

  # Normalise to one format so concatenation is a byte-level operation, trim
  # the silence espeak leaves on either end, and pad a hair so consecutive
  # cues in a 5-4-3-2-1 countdown never bleed into each other.
  ffmpeg -nostdin -loglevel error -y -i "$raw" \
    -af "silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.02,areverse,silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.02,areverse,apad=pad_dur=0.05,loudnorm=I=-16:TP=-1.5:LRA=11" \
    -ar 48000 -ac 1 "$clip"

  duration=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$clip")
  echo "file '$clip'" >> "$LIST"
  ENTRIES+=("$key $OFFSET $duration")
  OFFSET=$(python3 -c "print(round($OFFSET + $duration, 6))")
  printf "  %-8s %6.3fs\n" "$key" "$duration"
done

echo "Concatenating..."
ffmpeg -nostdin -loglevel error -y -f concat -safe 0 -i "$LIST" -ar 48000 -ac 1 "$WORK/sprite.wav"

# Two encodings because no single one plays everywhere: Opus in WebM is the
# smallest and is supported by Chrome and Firefox; AAC in MP4 covers Safari.
echo "Encoding..."
ffmpeg -nostdin -loglevel error -y -i "$WORK/sprite.wav" -c:a libopus -b:a 32k cues.webm
ffmpeg -nostdin -loglevel error -y -i "$WORK/sprite.wav" -c:a aac -b:a 48k -movflags +faststart cues.m4a

echo "Writing offsets..."
{
  echo "{"
  echo "  \"_comment\": \"Generated by generate.sh. Offsets and durations are seconds into the sprite.\","
  echo "  \"cues\": {"
  last=$(( ${#ENTRIES[@]} - 1 ))
  for i in "${!ENTRIES[@]}"; do
    read -r key offset duration <<< "${ENTRIES[$i]}"
    comma=","
    [[ $i -eq $last ]] && comma=""
    printf '    "%s": { "offset": %s, "duration": %s }%s\n' "$key" "$offset" "$duration" "$comma"
  done
  echo "  }"
  echo "}"
} > offsets.json

echo
echo "Done:"
ls -lh cues.webm cues.m4a offsets.json | awk '{printf "  %-14s %s\n", $9, $5}'
