// Code generated by cmd/gen-scoring-table. DO NOT EDIT.
//
// Point values mirrored from api/internal/scoring so the scoring screen can
// show a tap's worth immediately, without waiting for the server. The server
// remains authoritative: its total overwrites the optimistic one on every
// response, which is what applies the caps this table cannot know about
// (the 90:/5 top-five selection and the tiny-dog weekly ceiling).
//
// Regenerate with: go generate ./...

const TABLE = {
  junior: {
    standard: {
      "miss": { plain: 0, air: 0 },
      "0-10": { plain: 1, air: 1 },
      "10-20": { plain: 1, air: 1.5 },
      "20-30": { plain: 2, air: 2.5 },
      "30-40": { plain: 3, air: 3.5 },
      "40-50": { plain: 5, air: 5.5 },
      "out": { plain: 1, air: 1 },
    },
    tiny: {
      "miss": { plain: 0, air: 0 },
      "0-10": { plain: 2, air: 2 },
      "10-20": { plain: 2, air: 2.5 },
      "20-30": { plain: 3, air: 3.5 },
      "30-40": { plain: 4, air: 4.5 },
      "40-50": { plain: 6, air: 6.5 },
      "out": { plain: 2, air: 2 },
    },
  },
  handler: {
    standard: {
      "miss": { plain: 0, air: 0 },
      "0-10": { plain: 0, air: 0 },
      "10-20": { plain: 1, air: 1.5 },
      "20-30": { plain: 2, air: 2.5 },
      "30-40": { plain: 3, air: 3.5 },
      "40-50": { plain: 5, air: 5.5 },
      "out": { plain: 0, air: 0 },
    },
    tiny: {
      "miss": { plain: 0, air: 0 },
      "0-10": { plain: 0, air: 0 },
      "10-20": { plain: 2, air: 2.5 },
      "20-30": { plain: 3, air: 3.5 },
      "30-40": { plain: 4, air: 4.5 },
      "40-50": { plain: 6, air: 6.5 },
      "out": { plain: 0, air: 0 },
    },
  },
  master: {
    standard: {
      "miss": { plain: 0, air: 0 },
      "0-10": { plain: 0, air: 0 },
      "10-20": { plain: 1, air: 1.5 },
      "20-30": { plain: 2, air: 2.5 },
      "30-40": { plain: 3, air: 3.5 },
      "40-50": { plain: 5, air: 5.5 },
      "out": { plain: 0, air: 0 },
    },
    tiny: {
      "miss": { plain: 0, air: 0 },
      "0-10": { plain: 0, air: 0 },
      "10-20": { plain: 2, air: 2.5 },
      "20-30": { plain: 3, air: 3.5 },
      "30-40": { plain: 4, air: 4.5 },
      "40-50": { plain: 6, air: 6.5 },
      "out": { plain: 0, air: 0 },
    },
  },
  expert: {
    standard: {
      "miss": { plain: 0, air: 0 },
      "0-10": { plain: 0, air: 0 },
      "10-20": { plain: 1, air: 1.5 },
      "20-30": { plain: 2, air: 2.5 },
      "30-40": { plain: 3, air: 3.5 },
      "40-50": { plain: 5, air: 5.5 },
      "out": { plain: 0, air: 0 },
    },
    tiny: {
      "miss": { plain: 0, air: 0 },
      "0-10": { plain: 0, air: 0 },
      "10-20": { plain: 2, air: 2.5 },
      "20-30": { plain: 3, air: 3.5 },
      "30-40": { plain: 4, air: 4.5 },
      "40-50": { plain: 6, air: 6.5 },
      "out": { plain: 0, air: 0 },
    },
  },
};

/**
 * What one throw is worth, in points.
 *
 * @param {string} zone            zone key, e.g. "30-40"
 * @param {boolean} air            a clear four-paws-off catch
 * @param {object} team
 * @param {boolean} team.tiny
 * @param {string} team.division
 */
export function pointsFor(zone, air, { tiny = false, division = 'expert' } = {}) {
  const byTiny = TABLE[division] ?? TABLE.expert;
  const values = (tiny ? byTiny.tiny : byTiny.standard)[zone];
  if (!values) return 0;
  return air ? values.air : values.plain;
}

/** The scoring grid, furthest zone first. */
export const ZONE_BUTTONS = [
  { zone: "40-50", label: "40-50 yd", tone: "zone-5" },
  { zone: "30-40", label: "30-40 yd", tone: "zone-3" },
  { zone: "20-30", label: "20-30 yd", tone: "zone-2" },
  { zone: "10-20", label: "10-20 yd", tone: "zone-1" },
];
